---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: zeta-os
description: My personal Bazzite-based OS image for the family.

base-image: ghcr.io/ublue-os/bazzite-gnome
image-version: latest

modules:
  # MISSION 1: File Overlays (Bazzite/Wolf-OS style)
  - type: files
    files:
      - source: etc
        destination: /etc
      - source: usr
        destination: /usr
      - source: tmp/pia-backup.tar.xz
        destination: /tmp/pia-backup.tar.xz        

  # MISSION 2: Modular Repos and Packages
  - from-file: ../modules/repository.yml
  - from-file: ../modules/packages.yml
  
  # MISSION 3: Custom Assembly (The Script)
  - type: script
    scripts:
      - setup-zeta-os.sh

  # MISSION 4: Security
  - type: signing

